### ISSUE TITLE
What's the network-confg format?

### ISSUE THREAD

**Issue by simonwanghub** [atonkyra/tftp-conftool#1]
Network-confg is cfg?

**Comment by atonkyra** [comment]
Cisco switches do automatically ask for network-confg named file which is then provided by the script. Sadly this is a long-forgotten repo of mine related to prototyping a larger system.

Network-confg should contain a working running-configuration for cisco switches (as seen in `sh run`).

I'll close this and archive the repo as it is abandoned by me :)
